package server.connector.ftp;

public enum FTPErrorCode {
    CONNECTION_FAILED,
    LOGIN_FAILED,
    FILE_NOT_FOUND,
    FILE_RETRIEVE_ERROR,
    FILE_ALREADY_EXIST,
    FILE_SENDING_ERROR,
    FILE_DELETING_ERROR,
    DISCONNECTION_FAILED,
    FILE_NAMES_GETTING_ERROR
}
