package common.error.info;

public enum ErrorType {
    FTP_ERROR,
    WORKBOOK_LOCAL_FILE_READING_ERROR,
    WORKBOOK_SERVER_FILE_WRITING_ERROR,
    WORKBOOK_SERVER_FILE_READING_ERROR,
    SERVER_FILE_AND_LOCAL_FILE_STRUCTURE_NOT_EQUALS,
    CLIENT_REGION_ALREADY_IN_SERVER_FILE,
    LOCK_ERROR,
}
